language: go
services:
- "docker"
cache:
  directories:
    - ${TRAVIS_HOME}/gopath/bin
    - ${TRAVIS_HOME}/gopath/pkg
go:
  - 1.13.x
jobs:
  include:
  - stage: "Lint and tests"
    script: bash ./scripts/revive.sh
  - script: bash ./scripts/golangci-lint.sh
  - script: make tests
