name: build, test, lint

on:
  push:
    branches:
      - '*'

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  golang:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install musicmash and musicmashctl
        run:
          go install -v -mod=vendor ./cmd/...

      - name: Test whole code
        run:
          go test -v -mod=vendor ./internal/...

      - name: Install and run lintes
        run: |
          bash ./scripts/revive.sh
          bash ./scripts/golangci-lint.sh
