on: [pull_request]

name: Build and lint code on pull request

jobs:
  build:
    name: Build and lint code on pull request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Install binaries
        run: make install

      - name: Test whole code
        run: make test

      - name: Install and run lints
        run: make lint
